// Generated by https://quicktype.io

export interface PayloadPokemons {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}

export interface PayloadPokemon {
  id: string;
  name: string;
  picture: string;
  color?: string;
}
